FROM quay.io/strimzi/kafka:0.51.0-kafka-4.1.1
USER root
RUN mkdir -p /opt/kafka/plugins/manifest-codegen
COPY build/libs/connect-manifest-codegen-4.4.0-SNAPSHOT.jar \
     /opt/kafka/plugins/manifest-codegen/manifest-codegen.jar
USER 1001
